# Numpy
- Numpy is the core library for scientific computing in Python. It provides high-performance multidimensional array objects, and tools for working with these arrays. 

- A numpy **array** is a grid of values, usually of the same type, although technically you can store values of different types (this may complicate array operation). 
    - The number of dimensions is the **rank** of the array
    - The **shape** of an array is a tuple of integers giving the size of the array along each dimension
      * e.g. array([5, 2, 3]) has shape (3,) 
      * e.g. array([[5, 2, 3], [1,2,3]]) has shape (2,3)
    - Numpy arrays can be initialized from nested Python lists, and access elements using square brackets

![](https://raw.githubusercontent.com/devin19940107/My-Python-Notebook/master/supporting%20files/Images/matrix.jpg)

![](https://raw.githubusercontent.com/devin19940107/My-Python-Notebook/master/supporting%20files/Images/dimension.png)

In [2]:
import numpy as np # always import numpy 1st

# Creating an array

In [13]:
# 0-D Array
arr = np.array(42)

print(arr)

42


In [14]:
# 1-D Array
data1 = [1,2,3,4,5,6,7,8,9]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 2D Array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
#3D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Dimension

In [18]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


# Rank (shape) 

* Number of dimensions of the array is called rank of the array

In [35]:
print('42 rank is--->',arr.shape)
print('[[1,2,3,4,5,6,7,8,9]] rank is------>',arr1.shape)
print('[[1, 2, 3, 4], [5, 6, 7, 8]] rank is ----->',arr2.shape)
print('[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] rank is ----->',arr3.shape)


42 rank is---> ()
[[1,2,3,4,5,6,7,8,9]] rank is------> (9,)
[[1, 2, 3, 4], [5, 6, 7, 8]] rank is -----> (2, 4)
[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] rank is -----> (2, 2, 3)


# Type & Dtype

In [56]:
print('type of arr:',type(arr))
print('dtype of arr:',arr.dtype)
print('----------------------------------')
print('type of arr1:',type(arr1))
print('dtype of arr1:',arr1.dtype)
print('----------------------------------')
print('type of arr2:',type(arr2))
print('dtype of arr2:',arr2.dtype)
print('----------------------------------')
print('type of arr3:',type(arr3))
print('dtype of arr3:',arr3.dtype)

type of arr: <class 'numpy.ndarray'>
dtype of arr: int64
----------------------------------
type of arr1: <class 'numpy.ndarray'>
dtype of arr1: int64
----------------------------------
type of arr2: <class 'numpy.ndarray'>
dtype of arr2: int64
----------------------------------
type of arr3: <class 'numpy.ndarray'>
dtype of arr3: int64


In [54]:
arr4 = np.array([[1,2,3,4,5,6,7,8.5]]) # when there is a float, all data type converted to float
print('type of arr4:',type(arr4))
print('dtype of arr4:',arr4.dtype)

type of arr4: <class 'numpy.ndarray'>
dtype of arr4: float64


# Specical Maxtix / Array
#### *zeros*


<font color = green>numpy.zeros(shape, dtype=float, order='C'')  
    
* shape : Shape of the new array
* dtype : Data-type of the returned array. [optional]
* order: C - columon wise; R - row wise. [optional]

In [61]:
np.zeros(5) # np.zeros(shape)

array([0., 0., 0., 0., 0.])

In [62]:
np.zeros((3,2)) 

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### *ones*


<font color = green>numpy.ones(shape,dtype=None, order='C'')  
    
* shape : Shape of the new array
* dtype : Data-type of the returned array. [optional]
* order: C - columon wise; R - row wise. [optional]

In [59]:
np.ones(5)# np.ones(shape)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.ones((3,2)) 

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### *empty*

<font color = green>numpy.empty(shape, dtype=float, order='C'')  
    
* shape : Shape of the new array
* dtype : Data-type of the returned array. [optional]
* order: C - columon wise; R - row wise. [optional]

In [77]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.empty((3,3))

array([[ 2.31584178e+077, -2.68678219e+154,  3.95252517e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

#### *constant*

<font color = green>numpy.full(shape, fill_value, dtype=None, order='C')  
    
* shape : Shape of the new array
* fill_value : value to be filled
* dtype : Data-type of the returned array. [optional]
* order: C - columon wise; R - row wise. [optional]

In [80]:
np.full(5, 3) # np.full(shape, number)

array([3, 3, 3, 3, 3])

In [74]:
np.full((2,2), 7)

array([[7, 7],
       [7, 7]])

#### *identity matrix*
<font color = green>numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')  
    
* N : Number of rows in the output.
* M : Number of columns in the output.[optional]
* k : Index of the diagonal.[optional]
* dtype : Data-type of the returned array. [optional]
* order: C - columon wise; R - row wise. [optional]

In [89]:
np.eye(2) # passby one number generate a Square matrix

array([[1., 0.],
       [0., 1.]])

In [86]:
np.eye(3,2) # pass by a shape, it generate a matrix by shape

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [88]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])