# Numpy
- Numpy is the core library for scientific computing in Python. It provides high-performance multidimensional array objects, and tools for working with these arrays. 

- A numpy **array** is a grid of values, usually of the same type, although technically you can store values of different types (this may complicate array operation). 
    - The number of dimensions is the **rank** of the array
    - The **shape** of an array is a tuple of integers giving the size of the array along each dimension
      * e.g. array([5, 2, 3]) has shape (3,) 
      * e.g. array([[5, 2, 3], [1,2,3]]) has shape (2,3)
    - Numpy arrays can be initialized from nested Python lists, and access elements using square brackets

![](https://raw.githubusercontent.com/devin19940107/My-Python-Notebook/master/supporting%20files/Images/matrix.jpg)

In [2]:
import numpy as np # always import numpy 1st

# Creating an array

In [13]:
# 0-D Array
arr = np.array(42)

print(arr)

42


In [14]:
# 1-D Array
data1 = [1,2,3,4,5,6,7,8,9]
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# 2D Array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
#3D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Dimension

In [18]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


# Rank