# Pandas  


<div class="alert alert-info" style="margin: 20px">
                                     
* <font color= red> Data structures: </font>   
    Series: a one-dimensional labeled array ,<font color = green> it can be seen as an upgraded ndarray</font>    
    DataFrame: two-dimensional labeled data structure with columns ,<font color = green> it can be seen as an upgraded series</font>  
* <font color= red> Labeling: </font>  
    index: the name of each row  
    column name: the name of each column  

In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [3]:
# enable interactiveShell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Series
##### Series( data=None, index=None, dtype=None, name=None, copy=False, fastpath=False )

two ways to create a Series
* you can create a list by passing a 1-D array, by adding or or define index
* you can also create by passing a dictionary

In [14]:
# String
S=pd.Series(['1','2','3','4','5'])
S
S.values
S.index
S[0]+S[1]

0    1
1    2
2    3
3    4
4    5
dtype: object

array(['1', '2', '3', '4', '5'], dtype=object)

RangeIndex(start=0, stop=5, step=1)

'12'

In [16]:
# Interger in list
S = Series([1, 2, 3, 4, 5])
S
S.values
S.index
S[0]+S[1]

0    1
1    2
2    3
3    4
4    5
dtype: int64

array([1, 2, 3, 4, 5])

RangeIndex(start=0, stop=5, step=1)

3

In [17]:
# Boolean in list
S = Series([True, False, False,True,True])
S
S.values
S.index
S[0]+S[1]

0     True
1    False
2    False
3     True
4     True
dtype: bool

array([ True, False, False,  True,  True])

RangeIndex(start=0, stop=5, step=1)

True

In [21]:
# Float in tuple
S = Series(data  = (1.2,2.3,3.4,4.5,5.6))
S
S.values
S.index
S[0]+S[1]

0    1.2
1    2.3
2    3.4
3    4.5
4    5.6
dtype: float64

array([1.2, 2.3, 3.4, 4.5, 5.6])

RangeIndex(start=0, stop=5, step=1)

3.5

In [23]:
# Float in dictionary
S = Series(data  = {1:1.2,2:2.2,3:3.3,4:4.4,5:5.5})
S
S.values
S.index
S[0] + S[1] # beacuse we didn't assign S[0]

1    1.2
2    2.2
3    3.3
4    4.4
5    5.5
dtype: float64

array([1.2, 2.2, 3.3, 4.4, 5.5])

Int64Index([1, 2, 3, 4, 5], dtype='int64')

KeyError: 0

### Series operation

In [38]:
S = Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
S

d    4
b    7
a   -5
c    3
dtype: int64

In [39]:
S['a']

-5

In [40]:
S['d'] = 5
S

d    5
b    7
a   -5
c    3
dtype: int64

In [41]:
S > 0

d     True
b     True
a    False
c     True
dtype: bool

In [42]:
S[S > 0]

d    5
b    7
c    3
dtype: int64

In [43]:
S * 2

d    10
b    14
a   -10
c     6
dtype: int64

In [58]:
student = {'Student1': 99, 'Student2': 100, 'Student3': 20, 'Student4': np.NaN}
S = Series(student)
S

# you can copy value from S to S2 by retreiving index
index = ['Student1', 'Student2', 'Student3']
S2 = Series(student, index= index)
S2

Student1     99.0
Student2    100.0
Student3     20.0
Student4      NaN
dtype: float64

Student1     99.0
Student2    100.0
Student3     20.0
dtype: float64

In [68]:
S +S2

Student1    198.0
Student2    200.0
Student3     40.0
Student4      NaN
dtype: float64

### Null values

* `NaN` values numpy uses `np.isnan()`.

* `NaN` values pandas uses either .isna() or .isnull().

The NaN values are inherited from the fact that pandas is built on top of numpy

In [66]:
pd.isnull(S)
pd.isna(S)
Series.isnull(S)
Series.isna(S)
S.isnull()

Student1    False
Student2    False
Student3    False
Student4     True
dtype: bool

Student1    False
Student2    False
Student3    False
Student4     True
dtype: bool

Student1    False
Student2    False
Student3    False
Student4     True
dtype: bool

Student1    False
Student2    False
Student3    False
Student4     True
dtype: bool

Student1    False
Student2    False
Student3    False
Student4     True
dtype: bool

### Seies indexing / sclicing

there are three types of indexing:
1. normal:
    - S[ start:end:step, start:end:step]
    - same as indexing as NumPy ndaray
2. visible:
    - `.loc[]`
    - using index itself as searching pattern
    
3. invisible:
    - `.iloc[]`
    - using cardinal number of an indexas searching pattern
    
    
* <font color = red> since compare to orther data structure series index is an essential attribute, here we recommend using visible indexing `.loc[ ]`.</font>

In [86]:
dic = {'A':1,'B':2,'C':3,'D':4,'E':5} 
S = pd.Series(dic) # Now characters are index and numbers are value
S
S.index

A    1
B    2
C    3
D    4
E    5
dtype: int64

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [105]:
# quick slicing 
S.head()
S.tail()

A    1
B    2
C    3
D    4
E    5
dtype: int64

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [100]:
# normal way
S[1]

2

In [106]:
# loc
S.loc['A']
S.loc[1] # if you pass a value in it it will raice a error

1

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [102]:
# iloc
S.iloc[1]
S.iloc['A'] # If you pass index itself, it will raise a error

2

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [A] of <class 'str'>

In [104]:
# interval 
S.loc['A':'B'] # inclusive : inclusive
S.iloc[0:1] # inclusive : exclusive

A    1
B    2
dtype: int64

A    1
dtype: int64

# DataFrame

In [107]:
df = pd.DataFrame(np.random.randint(60,100, (5,4)), \
                  index=[1,2,3,4,5], \
                  columns=['A','B','C','D'])
df
# get first fiive rows
df.head(5)

# get last three rows
df.tail(3)

# get a column 
df.A  # OR df['A']
df['A']


# columns are Series
type(df.A)

A   B   C   D
1  93  74  63  92
2  64  66  81  96
3  89  89  78  83
4  88  93  97  88
5  64  83  64  74

A   B   C   D
1  93  74  63  92
2  64  66  81  96
3  89  89  78  83
4  88  93  97  88
5  64  83  64  74

A   B   C   D
3  89  89  78  83
4  88  93  97  88
5  64  83  64  74

1    93
2    64
3    89
4    88
5    64
Name: A, dtype: int64

1    93
2    64
3    89
4    88
5    64
Name: A, dtype: int64

pandas.core.series.Series

In [ ]:
df["DEPT"]=['CS','BIA','IS','BIA','BIA']
df