# Pandas  


<div class="alert alert-info" style="margin: 20px">
                                     
* <font color= red> Data structures: </font>   
    Series: a one-dimensional labeled array ,<font color = green> it can be seen as an upgraded ndarray</font>    
    DataFrame: two-dimensional labeled data structure with columns ,<font color = green> it can be seen as an upgraded series</font>  
* <font color= red> Labeling: </font>  
    index: the name of each row  
    column name: the name of each column  

In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [3]:
# enable interactiveShell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# 1. Series
##### Series( data=None, index=None, dtype=None, name=None, copy=False, fastpath=False )

two ways to create a Series
* you can create a list by passing a 1-D array, by adding or or define index
* you can also create by passing a dictionary

### 1.1 Basic syntax

In [14]:
# String
S=pd.Series(['1','2','3','4','5'])
S
S.values
S.index
S[0]+S[1]

0    1
1    2
2    3
3    4
4    5
dtype: object

array(['1', '2', '3', '4', '5'], dtype=object)

RangeIndex(start=0, stop=5, step=1)

'12'

In [16]:
# Interger in list
S = Series([1, 2, 3, 4, 5])
S
S.values
S.index
S[0]+S[1]

0    1
1    2
2    3
3    4
4    5
dtype: int64

array([1, 2, 3, 4, 5])

RangeIndex(start=0, stop=5, step=1)

3

In [17]:
# Boolean in list
S = Series([True, False, False,True,True])
S
S.values
S.index
S[0]+S[1]

0     True
1    False
2    False
3     True
4     True
dtype: bool

array([ True, False, False,  True,  True])

RangeIndex(start=0, stop=5, step=1)

True

In [21]:
# Float in tuple
S = Series(data  = (1.2,2.3,3.4,4.5,5.6))
S
S.values
S.index
S[0]+S[1]

0    1.2
1    2.3
2    3.4
3    4.5
4    5.6
dtype: float64

array([1.2, 2.3, 3.4, 4.5, 5.6])

RangeIndex(start=0, stop=5, step=1)

3.5

In [23]:
# Float in dictionary
S = Series(data  = {1:1.2,2:2.2,3:3.3,4:4.4,5:5.5})
S
S.values
S.index
S[0] + S[1] # beacuse we didn't assign S[0]

1    1.2
2    2.2
3    3.3
4    4.4
5    5.5
dtype: float64

array([1.2, 2.2, 3.3, 4.4, 5.5])

Int64Index([1, 2, 3, 4, 5], dtype='int64')

KeyError: 0

### 1.2 Series operation

#### 1.2.1  Series with number

In [12]:
S = Series([4, 7, -5, 3, None], index=['d', 'b', 'a', 'c','f'])
S

d    4.0
b    7.0
a   -5.0
c    3.0
f    NaN
dtype: float64

In [13]:
S * 2

d     8.0
b    14.0
a   -10.0
c     6.0
f     NaN
dtype: float64

In [14]:

S+10
S.add(10)
S.add(10, fill_value = 0)
S.add(10, fill_value = 100)

d    14.0
b    17.0
a     5.0
c    13.0
f     NaN
dtype: float64

d    14.0
b    17.0
a     5.0
c    13.0
f     NaN
dtype: float64

d    14.0
b    17.0
a     5.0
c    13.0
f    10.0
dtype: float64

d     14.0
b     17.0
a      5.0
c     13.0
f    110.0
dtype: float64

In [15]:
# Series is an upgraded version of ndarray
S = Series([1,2,3,4,None,np.nan])
S
None == np.nan # None type data is different with np.nan
S.sum()


ND = np.array([1,2,3,4,None,np.nan])
ND.sum() # none type data can not be sumed 

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    NaN
dtype: float64

False

10.0

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

#### 1.2.2. Series with Series


   <font color = green> * when calculating between two series, it automaticlly pair similar index, and only calculate the matched part</font>  
   <font color = green>  * it will concatenate all index with unpaired part return NaN.</font>

In [18]:
student = {'Student1': 99, 'Student2': 100, 'Student3': 20, 'Student4': np.NaN}
S = Series(student)
S

# you can copy value from S to S2 by retreiving index
index = ['Student1', 'Student2', 'Student3']
S2 = Series(student, index= index)
S2

# series addation
S + S2

Student1     99.0
Student2    100.0
Student3     20.0
Student4      NaN
dtype: float64

Student1     99.0
Student2    100.0
Student3     20.0
dtype: float64

Student1    198.0
Student2    200.0
Student3     40.0
Student4      NaN
dtype: float64

In [21]:
S1 = Series([1,2,3,4,5],index = [0,1,2,3,4])
S1
S2 = Series([11,22,33,44,55], index = [3,4,5,6,7])
S2

S1+S2

# if you want to retain all values in a Series, you can use add()
S1.add(S2, fill_value = 0)

0    1
1    2
2    3
3    4
4    5
dtype: int64

3    11
4    22
5    33
6    44
7    55
dtype: int64

0     NaN
1     NaN
2     NaN
3    15.0
4    27.0
5     NaN
6     NaN
7     NaN
dtype: float64

0     1.0
1     2.0
2     3.0
3    15.0
4    27.0
5    33.0
6    44.0
7    55.0
dtype: float64

### 1.3 Null values

* `NaN` values numpy uses `np.isnan()`.

* `NaN` values pandas uses either .isna() or .isnull().

The NaN values are inherited from the fact that pandas is built on top of numpy

In [118]:
# Series and dataframe share the same attribute
Series.isnull(S)
Series.isna(S)

pd.isnull(S)
pd.isna(S)

# build in function
S.isnull()



0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

0    False
1    False
2    False
3    False
4     True
5     True
dtype: bool

### 1.4 Seies indexing / sclicing

there are three types of indexing:
1. sclicing:
    - S[ start:end:step, start:end:step]
    - same as indexing as NumPy ndaray
2. visible indexing:
    - `.loc[]`
    - using index itself as searching pattern
    
3. invisible indexing:
    - `.iloc[]`
    - using cardinal number of an indexas searching pattern
    
    
* <font color = red> since compare to orther data structure series index is an essential attribute, here we recommend using visible indexing `.loc[ ]`.</font>

In [129]:
dic = {'A':1,'B':2,'C':3,'D':4,'E':5} 
S = pd.Series(dic) # Now characters are index and numbers are value
S
S.index

A    1
B    2
C    3
D    4
E    5
dtype: int64

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

#### 1.4.1 quick slicing 

In [130]:
# quick slicing 
S.head()
S.tail()

A    1
B    2
C    3
D    4
E    5
dtype: int64

A    1
B    2
C    3
D    4
E    5
dtype: int64

#### 1.4.2 slicinng

In [131]:
# slicinng
S[1]

2

#### 1.4.3 .loc[ ]

In [132]:
# loc
S.loc['A']
S.loc[1] # if you pass a value in it it will raice a error

1

TypeError: cannot do label indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

#### 1.4.4 .iloc[  ] 

In [133]:
# iloc
S.iloc[1]
S.iloc['A'] # If you pass index itself, it will raise a error

2

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [A] of <class 'str'>

#### 1.4.5 Boolean indexing

In [134]:
# Boolean indexing
s1 = Series([1,2,3,4,np.nan,None,7,8,9])
s1
s2 = s1.isnull()
s2
s3 = Series(['A','B','C','D','E','F','G','H','I'])
s3
s3[s2]

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    NaN
6    7.0
7    8.0
8    9.0
dtype: float64

0    False
1    False
2    False
3    False
4     True
5     True
6    False
7    False
8    False
dtype: bool

0    A
1    B
2    C
3    D
4    E
5    F
6    G
7    H
8    I
dtype: object

4    E
5    F
dtype: object

#### 1.4.6 Interval Difference

In [ ]:
# interval 
S.loc['A':'B'] # inclusive : inclusive
S.iloc[0:1] # inclusive : exclusive

# 2. DataFrame

* DataFrame is an upgraded version of Series, it can be seen as multiple Series sharing same index
* DataFrame also expend Series from 1 dimension to multiple dimension
    - row index: index
    - column index: column
    - cell : values


### 2.1 Basic Syntax

In [22]:
df = pd.DataFrame(np.random.randint(60,100, (5,4)), \
                  index=[1,2,3,4,5], \
                  columns=['A','B','C','D'])
df

A   B   C   D
1  68  75  82  96
2  80  64  90  99
3  68  60  79  87
4  90  62  65  85
5  87  71  74  92

In [23]:
df.index
df.columns
df.values

Int64Index([1, 2, 3, 4, 5], dtype='int64')

Index(['A', 'B', 'C', 'D'], dtype='object')

array([[68, 75, 82, 96],
       [80, 64, 90, 99],
       [68, 60, 79, 87],
       [90, 62, 65, 85],
       [87, 71, 74, 92]])

In [25]:
df.values.shape

(5, 4)

In [24]:
# get first fiive rows
df.head(5)

# get last three rows
df.tail(3)

# get a column 
df.A  # OR df['A']
df['A']


# columns are Series
type(df.A)

A   B   C   D
1  68  75  82  96
2  80  64  90  99
3  68  60  79  87
4  90  62  65  85
5  87  71  74  92

A   B   C   D
3  68  60  79  87
4  90  62  65  85
5  87  71  74  92

1    68
2    80
3    68
4    90
5    87
Name: A, dtype: int64

1    68
2    80
3    68
4    90
5    87
Name: A, dtype: int64

pandas.core.series.Series

In [30]:
# you can also define a Dataframe by using dictionary
df = DataFrame({'height':[6.6,5.5,6.3,6.8],\
                'age':[22,24,25,26],\
                'bodyfat':[0.4,0.2,0.25,0.3]}, 
               index = ['person1','person2','person3','person4'],
               # columns = ['h','a',b']
              )
df

height  age  bodyfat
person1     6.6   22     0.40
person2     5.5   24     0.20
person3     6.3   25     0.25
person4     6.8   26     0.30

In [32]:
# you can enlarge the dataset by adding new index and values
df["DEPT"]=['CS','BIA','IS','BIA']
df

height  age  bodyfat DEPT
person1     6.6   22     0.40   CS
person2     5.5   24     0.20  BIA
person3     6.3   25     0.25   IS
person4     6.8   26     0.30  BIA

### 2.2 DataFrame Indexing

In [49]:
age = df['age']
age
type(age) # each column is a series
age.index # and the index also embeded with each column(series)

person1    22
person2    24
person3    25
person4    26
Name: age, dtype: int64

pandas.core.series.Series

Index(['person1', 'person2', 'person3', 'person4'], dtype='object')

### 2.2.1 column indexing
- since each column is a series, it can be indexed, although each row has an index, it is not a series and means nothing (not an attribute)  
- column can not be sliced

In [54]:
# columnn wise
df.age
df['age']

# row wise
df.person1
df['person1']

person1    22
person2    24
person3    25
person4    26
Name: age, dtype: int64

person1    22
person2    24
person3    25
person4    26
Name: age, dtype: int64

AttributeError: 'DataFrame' object has no attribute 'person1'

### 2.2.2 row indexing

same as Series, DataFrame are able to be indexed by the following three types:  

- .ix[ ]  (is deprecated in python3, not recommend for future use)
- .loc[ ]  
- .iloc[ ]  
- <font color = red> number slicing alone is not supportted by DataFrame( df[row_start : row_stop, col_start: col_stop] )</font>

In [91]:
df[1:4,:] # slicing will raise an error

TypeError: unhashable type: 'slice'

In [92]:
df['person1':'person4'] # index sclicing canbe used

height  age  bodyfat DEPT
person1     6.6   22     0.40   CS
person2     5.5   24     0.20  BIA
person3     6.3   25     0.25   IS
person4     6.8   26     0.30  BIA

#### 2.2.2.1 .ix[  ]

In [68]:
df.ix[1]

# indexing followed by indexinng
df.ix[1][2]

# single indexing
df.ix[1,2]

/Users/shanjiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


height     5.5
age         24
bodyfat    0.2
DEPT       BIA
Name: person2, dtype: object

/Users/shanjiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.


0.2

/Users/shanjiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  import sys


0.2

In [74]:
row_1 = df.ix[1]
type(row_1) # it is also a Series (transposed a row into a Series, with column name as their index )

/Users/shanjiang/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


pandas.core.series.Series

#### 2.2.2.2 .loc[    ]

In [79]:
# .loc[ ]
# same as series, using index itself as searching pattern
df.loc['person1']
row_person1=df.loc['person1']
type(row_person1)

height     6.6
age         22
bodyfat    0.4
DEPT        CS
Name: person1, dtype: object

pandas.core.series.Series

In [87]:
# by using [ ] to adding multiple searching pattern

df.loc[['person1','person2']] # [] added both person1 and person2 and it returns a DataFrom not a Series


df.loc['person1','person2']

height  age  bodyfat DEPT
person1     6.6   22      0.4   CS
person2     5.5   24      0.2  BIA

KeyError: 'the label [person2] is not in the [index]'

In [89]:
# loc also can be used for slicing
df.loc['person1':'person4'] # inclusive

height  age  bodyfat DEPT
person1     6.6   22     0.40   CS
person2     5.5   24     0.20  BIA
person3     6.3   25     0.25   IS
person4     6.8   26     0.30  BIA

#### 2.2.2.3 .iloc[  ]

In [97]:
df.iloc[0]

height     6.6
age         22
bodyfat    0.4
DEPT        CS
Name: person1, dtype: object

In [95]:
df.iloc[0:5] # exclusive

height  age  bodyfat DEPT
person1     6.6   22     0.40   CS
person2     5.5   24     0.20  BIA
person3     6.3   25     0.25   IS
person4     6.8   26     0.30  BIA

In [36]:
135+33

168