# Pandas  


<div class="alert alert-info" style="margin: 20px">
                                     
* <font color= red> Data structures: </font>   
    Series: a one-dimensional labeled array  
    DataFrame: two-dimensional labeled data structure with columns  
* <font color= red> Labeling: </font>  
    index: the name of each row  
    column name: the name of each column  

In [2]:
from pandas import Series, DataFrame
import pandas as pd
import numpy as np

In [3]:
# enable interactiveShell
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### Series
##### Series( data=None, index=None, dtype=None, name=None, copy=False, fastpath=False )

In [14]:
# String
S=pd.Series(['1','2','3','4','5'])
S
S.values
S.index
S[0]+S[1]

0    1
1    2
2    3
3    4
4    5
dtype: object

array(['1', '2', '3', '4', '5'], dtype=object)

RangeIndex(start=0, stop=5, step=1)

'12'

In [16]:
# Interger in list
S = Series([1, 2, 3, 4, 5])
S
S.values
S.index
S[0]+S[1]

0    1
1    2
2    3
3    4
4    5
dtype: int64

array([1, 2, 3, 4, 5])

RangeIndex(start=0, stop=5, step=1)

3

In [17]:
# Boolean in list
S = Series([True, False, False,True,True])
S
S.values
S.index
S[0]+S[1]

0     True
1    False
2    False
3     True
4     True
dtype: bool

array([ True, False, False,  True,  True])

RangeIndex(start=0, stop=5, step=1)

True

In [21]:
# Float in tuple
S = Series(data  = (1.2,2.3,3.4,4.5,5.6))
S
S.values
S.index
S[0]+S[1]

0    1.2
1    2.3
2    3.4
3    4.5
4    5.6
dtype: float64

array([1.2, 2.3, 3.4, 4.5, 5.6])

RangeIndex(start=0, stop=5, step=1)

3.5

In [23]:
# Float in dictionary
S = Series(data  = {1:1.2,2:2.2,3:3.3,4:4.4,5:5.5})
S
S.values
S.index
S[0]+S[1] # we did assign S[0]

1    1.2
2    2.2
3    3.3
4    4.4
5    5.5
dtype: float64

array([1.2, 2.2, 3.3, 4.4, 5.5])

Int64Index([1, 2, 3, 4, 5], dtype='int64')

KeyError: 0