# linear algebra

In [96]:
import numpy as np

|sample|x1|x2|x3|x4|y|
|--|--|--|--|--|--|
|sample1|1|4|7|10|y1|
|sample2|2|5|8|11|y2|
|sample3|3|6|9|12|y3|

In [97]:
x = np.arange(1,13).reshape(3,4,order='f')
print(x,np.shape(x))

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]] (3, 4)


|--|theta|
|--|--|
|theta1|1|
|theta2|11|
|theta3|111|
|theta4|1111|

In [106]:
theta = [[11],
         [111],
         [1111],
         [11111]]
print(theta,np.shape(theta))

[[11], [111], [1111], [11111]] (4, 1)


# Multiplication

In [109]:
elementwise = theta*np.transpose(x)

elementwise

array([[    11,     22,     33],
       [   444,    555,    666],
       [  7777,   8888,   9999],
       [111110, 122221, 133332]])

In [110]:
h = sum(elementwise)
print(h,'.....',np.shape(h))

[119342 131686 144030] ..... (3,)


In [111]:
h[1]

131686

# Dot multiplication

In [107]:
new_h = np.dot(x,theta)
print(new_h,'.....',np.shape(new_h))

[[119342]
 [131686]
 [144030]] ..... (3, 1)


In [108]:
new_h[1]

array([131686])